(module
  (import "__builtins" "__wndpe_outline_begin" (func $__wndpe_outline_begin))
  (import "__builtins" "__wndpe_outline_end" (func $__wndpe_outline_end))
  (func $noop (result i32)
    (block $b0)
    (call $__wndpe_outline_begin)
    (block $b2)
    (call $__wndpe_outline_end)
    (block $b4)
    (i32.const 0)
  )
  (export "noop" (func $noop))
)
